language: node_js
before_script:
  - npm install -g gitbook
script: gitbook install && gitbook build
deploy:
  local-dir: _book
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: master